[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
actix= "0.13.5"
actix-web = "4.11.0"
actix-web-socket-io = "0.1.3"
env_logger = "0.11.8"
serde = {version = "1.0.219",features = ["default","derive"]}
serde_json = { version = "1.0.143" }
dotenv = "0.15.0"
